# Generated by Django 5.2.7 on 2025-11-06 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelto'), ('false_positive', 'Falsa Alerta'), ('non_compliant', 'Incumplimiento Real'), ('system_error', 'Error del Sistema')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
