# Generated by Django 5.2.7 on 2025-11-07 03:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deteccion', '0003_alert_resolution_notes_alert_resolution_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo_contenido', models.CharField(choices=[('texto', 'Texto'), ('pdf', 'PDF'), ('video', 'Video'), ('imagen', 'Imagen')], max_length=10, verbose_name='Tipo de Contenido')),
                ('contenido_texto', models.TextField(blank=True, null=True, verbose_name='Contenido Textual')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='capacitaciones/pdf/', verbose_name='Archivo PDF')),
                ('archivo_imagen', models.ImageField(blank=True, null=True, upload_to='capacitaciones/imagenes/', verbose_name='Imagen')),
                ('url_video', models.URLField(blank=True, null=True, verbose_name='URL de Video')),
                ('duracion_minutos', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración (minutos)')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('archivada', 'Archivada')], default='borrador', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('puntaje_minimo', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Puntaje Mínimo para Aprobar')),
                ('intentos_permitidos', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Intentos Permitidos')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacitaciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['-fecha_creacion'],
                'permissions': [('can_publish_capacitacion', 'Puede publicar capacitaciones'), ('can_create_evaluacion', 'Puede crear evaluaciones')],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('capacitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='deteccion.capacitacion', verbose_name='Capacitación')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('codigo_certificado', models.CharField(max_length=50, unique=True, verbose_name='Código de Certificado')),
                ('puntaje_final', models.IntegerField(verbose_name='Puntaje Final')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion.capacitacion', verbose_name='Capacitación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='IntentoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Intento')),
                ('puntaje_obtenido', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntaje Obtenido')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('numero_intento', models.IntegerField(default=1, verbose_name='Número de Intento')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion.evaluacion', verbose_name='Evaluación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Intento de Evaluación',
                'verbose_name_plural': 'Intentos de Evaluación',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto de la Pregunta')),
                ('tipo', models.CharField(choices=[('opcion_multiple', 'Opción Múltiple'), ('verdadero_falso', 'Verdadero/Falso')], max_length=20, verbose_name='Tipo de Pregunta')),
                ('puntaje', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Puntaje')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='deteccion.evaluacion', verbose_name='Evaluación')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200, verbose_name='Texto de la Opción')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='¿Es Correcta?')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='deteccion.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='deteccion.intentoevaluacion', verbose_name='Intento')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion.opcionrespuesta', verbose_name='Opción Seleccionada')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Usuario',
                'verbose_name_plural': 'Respuestas de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='ProgresoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('progreso_porcentaje', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progreso (%)')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deteccion.capacitacion', verbose_name='Capacitación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Progreso de Capacitación',
                'verbose_name_plural': 'Progresos de Capacitaciones',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('usuario', 'capacitacion')},
            },
        ),
    ]
